name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

  send-email-on-failure:
    needs: laravel-tests
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        env:
          SMTP_HOST: smtp.example.com
          SMTP_PORT: 587
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_TO: tongsreng@itc.edu.kh
          EMAIL_FROM: serlong012@gmail.com
        run: |
          echo "Subject: Build failed on branch ${{ github.ref }}" | sendmail -f $EMAIL_FROM $EMAIL_TO
          echo "Build failed on branch ${{ github.ref }}. Check details at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" | sendmail -f $EMAIL_FROM $EMAIL_TO
